/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp;

import javax.swing.ImageIcon;

/**
 *
 * @author gonza
 */
public class Ejercicio3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ejercicio3.class.getName());

    /**
     * Creates new form Ejercicio3
     */
    public Ejercicio3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        optigre = new javax.swing.JRadioButton();
        opperro = new javax.swing.JRadioButton();
        oppajaro = new javax.swing.JRadioButton();
        btMostrar = new javax.swing.JButton();
        lbMostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        buttonGroup1.add(optigre);
        optigre.setText("Tigre");
        optigre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optigreActionPerformed(evt);
            }
        });

        buttonGroup1.add(opperro);
        opperro.setText("Perro");
        opperro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opperroActionPerformed(evt);
            }
        });

        buttonGroup1.add(oppajaro);
        oppajaro.setText("Pajaro");
        oppajaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oppajaroActionPerformed(evt);
            }
        });

        btMostrar.setText("Mostrar");
        btMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarActionPerformed(evt);
            }
        });

        lbMostrar.setText("Imagen:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optigre)
                    .addComponent(opperro)
                    .addComponent(oppajaro)
                    .addComponent(btMostrar)
                    .addComponent(lbMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optigre)
                .addGap(18, 18, 18)
                .addComponent(opperro)
                .addGap(18, 18, 18)
                .addComponent(oppajaro)
                .addGap(18, 18, 18)
                .addComponent(btMostrar)
                .addGap(18, 18, 18)
                .addComponent(lbMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optigreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optigreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optigreActionPerformed

    private void btMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarActionPerformed
        String tigre = "src/tp/tigre.jpg";
        String perro = "src/tp/perro.jpg";
        String pajaro = "src/tp/pajaro.jpg";
        
        
        if(optigre.isSelected()) {
            lbMostrar.setIcon(new ImageIcon(getClass().getResource("/tp/tigre.jpg")));
        } else if(opperro.isSelected()){
            lbMostrar.setIcon(new ImageIcon(getClass().getResource("/tp/perro.jpg")));
    } else {
            lbMostrar.setIcon(new ImageIcon(getClass().getResource("/tp/pajaro.jpg")));
        }
    }//GEN-LAST:event_btMostrarActionPerformed

    private void opperroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opperroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opperroActionPerformed

    private void oppajaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oppajaroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oppajaroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ejercicio3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMostrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMostrar;
    private javax.swing.JRadioButton oppajaro;
    private javax.swing.JRadioButton opperro;
    private javax.swing.JRadioButton optigre;
    // End of variables declaration//GEN-END:variables
}
